import type { AppSettings, ReplaceMapConfig } from './types';

export const defaultSettings: AppSettings = {
  apiUrl: 'http://104.168.109.197:8317/v1/chat/completions',
  apiKey: 'sk-001',
  model: 'gemini-3-flash-preview',
  targetKeyword: '光明',
  trimLastPageForLawyerLetter: true,
  writeIntermediateJsons: true,
  debug: false,
  imageAlign: 'left',
  imageWidthCm: undefined,
  imageHeightCm: undefined,
};

export const initialReplaceMapConfig: ReplaceMapConfig = {
  schema_version: '1.0',
  name: '光明眼镜案件默认替换配置',
  description: '将 Defandent、DemandLetter 和 logical 的抽取结果转换为 Word 替换所需的 replace_map。',
  on_missing: 'empty',
  mappings: {
    '[--需要替换的被告--]': {
      mode: 'path',
      source: 'Defandent',
      path: ['企业名称', 0, 'value'],
      default: '',
      required: true,
      editable: true,
      description: '从企业报告中读取被告名称',
    },
    '[--需要替换的被告2--]': {
      mode: 'path',
      source: 'Defandent',
      path: ['企业名称', 0, 'value'],
      default: '',
      required: false,
      editable: true,
      description: '模板别名：第二处被告名称',
    },
    '[--需要替换的统一社会信用代码--]': {
      mode: 'path',
      source: 'Defandent',
      path: ['统一社会信用代码', 0, 'value'],
      default: '',
      required: true,
      editable: true,
      description: '从企业报告中读取统一社会信用代码',
    },
    '[--需要替换的住所--]': {
      mode: 'path',
      source: 'Defandent',
      path: ['住所', 0, 'value'],
      default: '',
      required: true,
      editable: true,
      description: '从企业报告中读取住所',
    },
    '[--需要替换的住所2--]': {
      mode: 'path',
      source: 'Defandent',
      path: ['住所', 0, 'value'],
      default: '',
      required: false,
      editable: true,
      description: '模板别名：第二处住所',
    },
    '[--需要替换的成立日期--]': {
      mode: 'path',
      source: 'Defandent',
      path: ['成立日期', 0, 'value'],
      default: '',
      required: true,
      editable: true,
      description: '从企业报告中读取成立日期',
    },
    '[--需要替换的成立日期2--]': {
      mode: 'path',
      source: 'Defandent',
      path: ['成立日期', 0, 'value'],
      default: '',
      required: false,
      editable: true,
      description: '模板别名：第二处成立日期',
    },
    '[--需要替换的经营范围--]': {
      mode: 'path',
      source: 'Defandent',
      path: ['经营范围', 0, 'value'],
      default: '',
      required: false,
      editable: true,
      description: '从企业报告中读取经营范围',
    },
    '[--需要替换的法定代表人--]': {
      mode: 'path',
      source: 'Defandent',
      path: ['法定代表人', 0, 'value'],
      default: '',
      required: true,
      editable: true,
      description: '从企业报告中读取法定代表人',
    },
    '[--需要替换的联系电话--]': {
      mode: 'path',
      source: 'Defandent',
      path: ['联系电话', 0, 'value'],
      default: '',
      required: false,
      editable: true,
      description: '从企业报告中读取联系电话，缺失时留空',
    },
    '[--需要替换的侵权事实--]': {
      mode: 'path',
      source: 'DemandLetter',
      path: ['侵权事实', 0, 'value'],
      default: '',
      required: true,
      editable: true,
      description: '从律师函抽取结果中读取侵权事实',
    },
    '[--需要替换的侵权事实1--]': {
      mode: 'path',
      source: 'DemandLetter',
      path: ['侵权事实', 0, 'value'],
      default: '',
      required: false,
      editable: true,
      description: '模板别名：第二处侵权事实',
    },
    '[--需要替换的律师函日期--]': {
      mode: 'path',
      source: 'DemandLetter',
      path: ['律师函日期', 0, 'value'],
      default: '',
      required: false,
      editable: true,
      description: '从律师函抽取结果中读取律师函日期',
    },
    '[--需要替换的法院名称--]': {
      mode: 'literal',
      value: '天津市和平区人民法院',
      default: '',
      required: false,
      editable: true,
      description: '固定法院名称示例',
    },
    '[--需要替换的诉请金额--]': {
      mode: 'literal',
      value: '10',
      default: '10',
      required: false,
      editable: true,
      description: '默认诉请金额（万元）',
    },
    '[--需要替换的侵权公司信息--]': {
      mode: 'template',
      template: '被告{{name}}，成立于{{date}}，住所地为{{address}}，经营范围包括{{scope}}。',
      vars: {
        name: { mode: 'path', source: 'Defandent', path: ['企业名称', 0, 'value'], default: '' },
        date: { mode: 'path', source: 'Defandent', path: ['成立日期', 0, 'value'], default: '' },
        address: { mode: 'path', source: 'Defandent', path: ['住所', 0, 'value'], default: '' },
        scope: { mode: 'path', source: 'Defandent', path: ['经营范围', 0, 'value'], default: '' },
      },
      default: '',
      required: false,
      editable: true,
      description: '由多个企业字段拼接成侵权公司信息',
    },
    '[--需要替换的案由--]': {
      mode: 'path',
      source: 'logical',
      path: ['案由', 0, 'value'],
      default: '',
      required: false,
      editable: true,
      description: '从 logical 中读取自动推导案由',
    },
    '[--需要替换的逻辑判断1--]': {
      mode: 'path',
      source: 'logical',
      path: ['案由', 0, 'value'],
      default: '',
      required: false,
      editable: true,
      description: '模板别名：案由',
    },
    '[--需要替换的诉讼请求三--]': {
      mode: 'path',
      source: 'logical',
      path: ['诉讼请求三', 0, 'value'],
      default: '',
      required: false,
      editable: true,
      description: '从 logical 中读取自动推导的第三项诉请',
    },
    '[--需要替换的逻辑判断2--]': {
      mode: 'path',
      source: 'logical',
      path: ['诉讼请求三', 0, 'value'],
      default: '',
      required: false,
      editable: true,
      description: '模板别名：第三项诉请',
    },
    '[--需要替换的不正当竞争事实段--]': {
      mode: 'path',
      source: 'logical',
      path: ['不正当竞争事实段', 0, 'value'],
      default: '',
      required: false,
      editable: true,
      description: '从 logical 中读取自动推导的不正当竞争事实段',
    },
    '[--需要替换的逻辑判断3--]': {
      mode: 'path',
      source: 'logical',
      path: ['不正当竞争事实段', 0, 'value'],
      default: '',
      required: false,
      editable: true,
      description: '模板别名：不正当竞争事实段',
    },
  },
};

export const mockDefandent = {
  企业名称: [{ value: '天津市清雅光明眼镜店', source: '8.国家企业信用信息公示系统-企业报告.md' }],
  统一社会信用代码: [{ value: '92120104MA05XW2R2L', source: '8.国家企业信用信息公示系统-企业报告.md' }],
  法定代表人: [{ value: '吴李勇', source: '8.国家企业信用信息公示系统-企业报告.md' }],
  成立日期: [{ value: '2005年11月28日', source: '8.国家企业信用信息公示系统-企业报告.md' }],
  住所: [{ value: '南开区白堤路157号', source: '8.国家企业信用信息公示系统-企业报告.md' }],
  经营范围: [{ value: '一般项目：眼镜销售（不含隐形眼镜）；日用百货销售；新鲜蔬菜批发；新鲜水果零售。', source: '8.国家企业信用信息公示系统-企业报告.md' }],
  联系电话: [{ value: '', source: '8.国家企业信用信息公示系统-企业报告.md' }],
};

export const mockDemandLetter = {
  侵权事实: [{
    value: '其在经营眼镜店的门店招牌、店内装饰装潢、眼镜柜、眼镜盒、包装袋等上面，大量使用了“光明”作为商标标识。',
    source: '天津市清雅光明眼镜店-律师函.md',
    source_text: '你方在该店铺的门店招牌、店内装饰装潢、眼镜柜、眼镜盒、包装袋等经营场所和经营活动中，使用了“老光明”标识。',
    paragraph_id: 3,
  }],
  律师函日期: [{ value: '', source: '天津市清雅光明眼镜店-律师函.md' }],
};

export const mockLogical = {
  案由: [{ value: '侵害商标权及不正当竞争纠纷', source: 'logical' }],
  诉讼请求三: [{ value: '三、判令被告立即停止不正当竞争行为，即立即变更企业名称，变更后的企业名称中不得含有“光明”文字；', source: 'logical' }],
  不正当竞争事实段: [{ value: '另外，被告自2005年11月28日开始，将“光明”文字作为其企业名称的字号使用并持续至今，用于案涉眼镜店的经营，构成了不正当竞争。', source: 'logical' }],
};

export const mockOcrMarkdown = {
  enterpriseReport: `# 企业报告 OCR

企业名称：天津市清雅光明眼镜店
统一社会信用代码：92120104MA05XW2R2L
法定代表人：吴李勇`,
  lawyerLetter: `# 律师函 OCR

近日，据我委托人反馈，你方在天津市红桥区丁字沽风采里附近开设了一家销售眼镜的店铺。`,
};
